<?php

namespace AppBundle\Repository;

/**
 * ChiffreAffaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChiffreAffaireRepository extends \Doctrine\ORM\EntityRepository
{
}
