<?php

namespace AppBundle\Repository;

/**
 * ContenanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContenanceRepository extends \Doctrine\ORM\EntityRepository
{
}
