<?php

namespace AppBundle\Repository;

/**
 * DroitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DroitsRepository extends \Doctrine\ORM\EntityRepository
{
}
