<?php

namespace AppBundle\Repository;

/**
 * EmplacementStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmplacementStockRepository extends \Doctrine\ORM\EntityRepository
{
}
