<?php

namespace AppBundle\Repository;

/**
 * IdentifiantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentifiantsRepository extends \Doctrine\ORM\EntityRepository
{
}
