<?php

namespace AppBundle\Repository;

/**
 * LigneEncaissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneEncaissementRepository extends \Doctrine\ORM\EntityRepository
{
}
