<?php

namespace AppBundle\Repository;

/**
 * LigneStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneStockRepository extends \Doctrine\ORM\EntityRepository
{
}
