<?php

namespace AppBundle\Repository;

/**
 * LigneTicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneTicketRepository extends \Doctrine\ORM\EntityRepository
{
}
