<?php

namespace AppBundle\Repository;

/**
 * RelationTaxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationTaxeRepository extends \Doctrine\ORM\EntityRepository
{
}
