<?php

namespace AppBundle\Repository;

/**
 * RessourcesHumainesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourcesHumainesRepository extends \Doctrine\ORM\EntityRepository
{
}
