<?php

namespace AppBundle\Repository;

/**
 * TaxationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxationRepository extends \Doctrine\ORM\EntityRepository
{
}
