<?php

namespace EPub\EPubBundle\Repository;

/**
 * TypeTaxeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTaxeRepository extends \Doctrine\ORM\EntityRepository
{
}
